import { ToolkitUseClipboard, ToolkitUseClipboardOptions } from './clip/index'
import { uniqueOptionsArr, uniqueValueArr, deepClone } from './array/index'
import { formatDate } from './date/index'
import { transformDecimal, toPercent, toPoint } from './decimal/index'
import { frontUrlDownload, dataStreamDownloadExcelOrPdf } from './download/index'
import { padStartZero } from './string/index'
// 后面给加上命名空间
import {
  isUndef,
  isDef,
  isTrue,
  isFalse,
  isPrimitive,
  isObject,
  isPromise,
  toRawType,
  hasOwn,
  toNumber,
  isPlainObject,
  toString,
  toArray,
  extend,
  toObject,
  cached,
  capitalize,
  hyphenate,
  camelize,
  makeMap,
  looseEqual,
  remove,
  looseCompareArrays,
  def,
  objectToString,
  toTypeString,
  isArray,
  isMap,
  isSet,
  isDate,
  isFunction,
  isString,
  isSymbol,
  isIntegerKey,
  invokeArrayFns,
  hasChanged
} from './shared/index'

import {
  getColor,
  eventUtils,
  addClass,
  removeClass,
  getElementLeft,
  getElementTop,
  getOffset,
  getViewport,
  outputAttributes,
} from './dom/index'

export {
  ToolkitUseClipboard,
  ToolkitUseClipboardOptions,
  uniqueOptionsArr,
  uniqueValueArr,
  deepClone,
  formatDate,
  transformDecimal,
  toPercent,
  toPoint,
  frontUrlDownload,
  dataStreamDownloadExcelOrPdf,
  padStartZero,
  isUndef,
  isDef,
  isTrue,
  isFalse,
  isPrimitive,
  isObject,
  isPromise,
  toRawType,
  hasOwn,
  toNumber,
  isPlainObject,
  toString,
  toArray,
  extend,
  toObject,
  cached,
  capitalize,
  hyphenate,
  camelize,
  makeMap,
  looseEqual,
  remove,
  looseCompareArrays,
  def,
  objectToString,
  toTypeString,
  isArray,
  isMap,
  isSet,
  isDate,
  isFunction,
  isString,
  isSymbol,
  isIntegerKey,
  invokeArrayFns,
  hasChanged,
  getColor,
  eventUtils,
  addClass,
  removeClass,
  getElementLeft,
  getElementTop,
  getOffset,
  getViewport,
  outputAttributes,
}